# AgaCommands - Configuração
# Aliases para o comando principal
main-command-aliases:
  - agacommands
  - hcommands

messages:
  reload: "&fAga&bCommands &8- &fConfiguração recarregada com sucesso!"
  blocked-command: "&cComando desconhecido ou inexistente."
  no-permission: "&cVocê não tem permissão para fazer isso."

  help:
    - ""
    - "&f Aga&bCommands &8- &7Lista de Comandos &c(STAFF)"
    - ""
    - "&8 ➡ &f/agacommands reload &8- &7Recarrega a configuração."
    - "&8 ➡ &f/agacommands <comando> <atalho> &8- &7Cria um atalho."
    - ""

aliases:
  voar: fly
  lobby: server lobby

blocked-commands:
  - "/pl"
  - "/plugins"
  - "/ver"
  - "/version"
  - "/about"

# Sistema de Anti-Tab
tab-settings:
  enabled: true

  # Lista de comandos onde o TAB será PERMITIDO (Whitelist)
  # Coloque apenas o início do comando.
  allowed-commands:
    - "/tpa"
    - "/tpaccept"
    - "/tell"
    - "/msg"
    - "/g"
    - "/l"
    - "/money"